<?php

session_start();

if (!isset($_SESSION['adminId'])) {
    header('location:logout.php');
}

?>

<!doctype html>
<html>

<head>
    <title>Exam Seat Allotment | Admin</title>
    <!-- <link href="css/style.css" rel="stylesheet" type="text/css"> -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.7/css/mdb.min.css" rel="stylesheet">
    <!-- sweetalert css cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/sweetalert2.min.css">
    <style>
        h2 {
            font-size: 22px;
            margin-top: -15%;
        }

        .jumbotron {
            border-radius: 2.125rem;
        }

        .jumbotron:hover {
            -webkit-transform: translate(5px, 15px);
            -webkit-box-shadow: inset 0 0 10px #000000;
            cursor: pointer;
        }


        .btn1 {
            margin-top: 25%;
            margin-left: 5%;
        }
    </style>
</head>

<body>
    <!-- Image and text -->
    <nav class="navbar navbar-dark primary-color">
        <a class="navbar-brand" href="#">
            <img src="assets/images/logo.jpg" height="60" width="60" style="border-radius:50%;" class="d-inline-block align-top" alt="mdb logo"> P.A. College of Engineering Mangaluru | Admin
        </a>
        <a class="btn btn-light" href="admin.php"> back <i class="fas fa-arrow-circle-left"></i></a>
    </nav><br>

    <?php

    include('connection.php');

    $query1 = "SELECT * FROM facultylist AS FL WHERE FL.status = '0'";
    $query1Result = mysqli_query($conn, $query1);

    $query2 = "SELECT * FROM facultySlots WHERE slotNumber = 'SLOT1'";
    $query2Result = mysqli_query($conn, $query2);

    $query3 = "SELECT * FROM facultySlots WHERE slotNumber = 'SLOT2'";
    $query3Result = mysqli_query($conn, $query3);
    
    $totalFacultyCount = mysqli_num_rows($query1Result);
    $totalFacultyCount_SLOT1 = ceil(mysqli_num_rows($query1Result)/2);
    $totalFacultyCount_SLOT2 = $totalFacultyCount - $totalFacultyCount_SLOT1;
    $currentFacultyCount_SLOT1 = mysqli_num_rows($query2Result);
    $currentFacultyCount_SLOT2 = mysqli_num_rows($query3Result);
    $currentFacultyCount = $currentFacultyCount_SLOT1 + $currentFacultyCount_SLOT2;
    $pendingFaculty = $totalFacultyCount - $currentFacultyCount;

    $array_facultySlot1 = array();
    $array_facultySlot2 = array();
    
    while ($query2ResultRow = mysqli_fetch_array($query2Result)) {
        array_push($array_facultySlot1,$query2ResultRow['facultyId']);
    }

    while ($query3ResultRow = mysqli_fetch_array($query3Result)) {
        array_push($array_facultySlot2,$query3ResultRow['facultyId']);
    }

    echo '
    <h3 style="text-align:center"> AutoGenerated Non-DCS Duty </h3>
    <table class="table table-bordered" style="text-align:center;">
        <thead class="black white-text">
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Slot Number</th>
                <th scope="col">Faculty Name</th>
            </tr>
        </thead>
        <tbody>
    ';

    

    //check if all faculties are respectively opted either Slot1 or Slot2
    if(($currentFacultyCount_SLOT1 != $totalFacultyCount_SLOT1) && ($currentFacultyCount_SLOT2 != $totalFacultyCount_SLOT2) && ($pendingFaculty != 0)){
        // Truncate table before use
        $truncatefacultyDuty = mysqli_query($conn,"TRUNCATE TABLE facultyDuty");
        
        $query4 = "SELECT * FROM generatedSlots";
        $query4Result = mysqli_query($conn, $query4);
        $index_facultySlot1=0;
        $index_facultySlot2=0;

        while($query4ResultRow = mysqli_fetch_array($query4Result)){
            $date = $query4ResultRow['date'];
            $slotCount = $query4ResultRow['slotCount'];
            $slotNumber = $query4ResultRow['slotNumber'];     
            $slotIndex = 0;   

        echo '
            <tr>
            <td style="font-weight:bold;">' . substr($date,0,2).'-'.substr($date,2,2).'-'.substr($date,4,2).' ['.substr($date,6).']</td>
            <td style="font-weight:bold;">' . $slotNumber . '</td>
            <td style="font-weight:bold;">
                    <ul>
                    
        ';
                
            while($slotIndex < $slotCount){ 
                if($slotNumber == 'SLOT1'){
                    if($index_facultySlot1 == count($array_facultySlot1)){
                        $index_facultySlot1 = 0;
                    }
                    $sql = mysqli_query($conn,"INSERT INTO facultyDuty(`date`,`slotNumber`,`facultyId`)VALUES('$date','$slotNumber','$array_facultySlot1[$index_facultySlot1]')");

                    $sqlName = "SELECT * FROM facultylist WHERE facultyId = '$array_facultySlot1[$index_facultySlot1]'";
                    $sqlNameResult = mysqli_query($conn, $sqlName);
                    $sqlNameResultRow = mysqli_fetch_array($sqlNameResult);

                    echo('<li>'.$sqlNameResultRow["name"].'&nbsp; ['.$array_facultySlot1[$index_facultySlot1].']</li>');
                    $index_facultySlot1++;
                }
                if($slotNumber == 'SLOT2'){
                    if($index_facultySlot2 == count($array_facultySlot2)){
                        $index_facultySlot2 = 0;
                    }
                    $sql = mysqli_query($conn,"INSERT INTO facultyDuty(`date`,`slotNumber`,`facultyId`)VALUES('$date','$slotNumber','$array_facultySlot2[$index_facultySlot2]')");

                    $sqlName = "SELECT * FROM facultylist WHERE facultyId = '$array_facultySlot2[$index_facultySlot2]'";
                    $sqlNameResult = mysqli_query($conn, $sqlName);
                    $sqlNameResultRow = mysqli_fetch_array($sqlNameResult);

                    echo('<li>'.$sqlNameResultRow["name"].'&nbsp; ['.$array_facultySlot2[$index_facultySlot2].']</li>');
                    $index_facultySlot2++;
                }
  
                $slotIndex++;
            }
        
        echo '
            </ul>
            </td>
            </tr>
        ';
        }
        
    } else {
        echo '
        <tr>
        <td colspan="3"> Waiting for faculties to pick their slots... ('.$pendingFaculty.' pending)</td>
        </tr>
        ';
    }
    echo '
    </tbody> </table><br><br><br><br>
    ';



    // echo($totalFacultyCount); echo(' = '); echo($totalFacultyCount_SLOT1); echo(' + '); echo($totalFacultyCount_SLOT2); echo('<br>');
    // echo($currentFacultyCount); echo(' = '); echo($currentFacultyCount_SLOT1); echo(' + '); echo($currentFacultyCount_SLOT2); echo('<br>');
    // print_r($array_facultySlot1); echo('<br>'); print_r($array_facultySlot2);



    // **************************************************************************************** //

    $sql3 = "SELECT * FROM facultylist AS FL WHERE FL.status = '0'";
    $sql3Result = mysqli_query($conn, $sql3);

    $sql2 = "SELECT * FROM facultySlots AS FS, facultylist AS FL WHERE FS.facultyId = FL.facultyId ORDER BY FS.slotNumber";
    $sql2Result = mysqli_query($conn, $sql2);

    echo '
    <h3 style="text-align:center">Current Status of Slots</h3>
    <table class="table table-bordered" style="text-align:center;">
        <thead class="black white-text">
            <tr>
                <th scope="col">Faculty ID</th>
                <th scope="col">Faculty Name</th>
                <th scope="col">Slot Number</th>
            </tr>
        </thead>
        <tbody>
    ';

    while ($sql2ResultRow = mysqli_fetch_array($sql2Result)) {
        $facultyId = $sql2ResultRow['facultyId'];
        $facultyName = $sql2ResultRow['name'];
        $slotNumber = $sql2ResultRow['slotNumber'];
        echo '
            <tr>
            <td style="font-weight:bold;">' . $facultyId . '</td>
            <td style="font-weight:bold;">' . $facultyName . '</td>
            <td style="font-weight:bold;">' . $slotNumber . '</td>
    
        ';
    }


    echo '
    </tbody> </table><br><br><br><br>
    ';

    // Truncate table before use
    $truncategeneratedSlots = mysqli_query($conn,"TRUNCATE TABLE generatedSlots");
    
    $sql1 = "SELECT * FROM calculateddata WHERE student1 != 0 OR student2 != 0";
    $calculatedDataResult = mysqli_query($conn, $sql1);
    $rowByTwo = ceil(mysqli_num_rows($calculatedDataResult)/2);
    $counter = $rowByTwo;

    while ($calculatedDataResultRow = mysqli_fetch_array($calculatedDataResult)) {
        $date = $calculatedDataResultRow['date'];
        $sub1 = $calculatedDataResultRow['sub1'];
        $student1 = $calculatedDataResultRow['student1'];
        $sub2 = $calculatedDataResultRow['sub2'];
        $student2 = $calculatedDataResultRow['student2'];
        $slots = 0;
        $releiving = 0;
        if($student1 != 0) {
            $slots = ceil($student1/30);
            $releiving = ceil($slots/4);
        }
        if($student2 != 0){
            $slots = $slots + ceil($student2/30);
            $releiving = $releiving + ceil($slots/4); 
        }
        $totalSlots = $slots + $releiving;

        if($counter != 0){
            $sql = mysqli_query($conn,"INSERT INTO generatedSlots(`date`,`slotCount`,`slotNumber`)VALUES('$date','$totalSlots','SLOT1')");
            $counter--;
        } else {
            $sql = mysqli_query($conn,"INSERT INTO generatedSlots(`date`,`slotCount`,`slotNumber`)VALUES('$date','$totalSlots','SLOT2')");
        }

        
    }

    $sql2 = "SELECT * FROM generatedSlots";
    $generatedSlotsResult = mysqli_query($conn, $sql2);

    echo '
    <h3 style="text-align:center">Generated Slots</h3>
    <table class="table table-bordered" style="text-align:center;">
        <thead class="black white-text">
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Slot Count</th>
                <th scope="col">Slot Number</th>
            </tr>
        </thead>
        <tbody>
    ';
    $totalSlotsGenerated = 0;
    while ($generatedSlotsResultRow = mysqli_fetch_array($generatedSlotsResult)) {
        $date = $generatedSlotsResultRow['date'];
        $slotCount = $generatedSlotsResultRow['slotCount'];
        $slotNumber = $generatedSlotsResultRow['slotNumber'];

        $totalSlotsGenerated = $totalSlotsGenerated + $slotCount;
        echo '
            <tr>
            <td style="font-weight:bold;">' . substr($date,0,2).'-'.substr($date,2,2).'-'.substr($date,4,2).' ['.substr($date,6).']</td>
            <td style="font-weight:bold;">' . $slotCount . '</td>
            <td style="font-weight:bold;">' . $slotNumber . '</td>
    
        ';
    }
    echo '
    </tbody> </table>
    ';


    $dutyCount = mysqli_num_rows($calculatedDataResult);
    echo '<script type="text/javascript">';
    echo 'setTimeout(function () { sweetAlert("<b>Summary","'.$dutyCount.' sessions and '.$totalSlotsGenerated.' slots are generated.<br> '.$currentFacultyCount.' faculties chose their slot.<br> '.$pendingFaculty.' faculties pending to select slot</b>");';
    echo '}, 500);</script>';

    ?>


    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.7/js/mdb.min.js"></script>
    <!-- sweetalert js cdn -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/sweetalert2.min.js"></script>
</body>

</html>